---
title: "Where I Am Currently With The PDLC Course"
subtitle: I have no idea
description: An update
author: "Abdullah Zeeshan"
date: "2023-06-21"
categories: [general]
reading-time: True
toc: true
fig-align: center
fig-cap-location: bottom
---

***Unlike most of the MOOCs, the PDLC course is not something that you just finish off in 8 weeks and get done with it!***

I found myself going back in loops multiple times. Someimes when I am in lesson 5, I go back to lesson 1, then lesson 4, then I read chapter 4, and so on! I have embraced this. Initially, it was pretty darn confusing. I heard Jeremy say this, that often students go back in multiple loops with the course. I said to myself, maybe if I finish a lesson *nicely* then I would not feel the need of coming back. It is not like that. That is not how it works. Revisiting chapter 1 when you are in Week 5 feels like you have found a new treasure. You ask yourself, "How the hell did I miss this?!" Maybe you didn't. It is only after you have gone till Week 5, you have got this new stream of thoughts that gives you insights. 

All I know is staying with the course, engaging with it every single day, treating it like a journey, and not giving up will help me finish it succesfully one day.
