project:
  type: website

website:
  site-url: https://zed4zee.github.io/learning-ai
  search:
    location: navbar
    type: overlay
  favicon: favicon.jpg
  navbar:
    title: "Abdullah Zeeshan"
    right:
      - text: "Notes"
        menu:
          - python.qmd
          - linux.qmd
          - deep-learning.qmd
      - icon: github
        href: https://github.com/zed4zee
      - icon: rss
        href: index.xml
  page-footer:
    left:
      - text: © 2023-present.
  page-navigation: true
  reader-mode: true
  back-to-top-navigation: true
format:
  html:
    theme: default
    toc: true

